/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BooksRouteImport } from './routes/books'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BooksNewRouteImport } from './routes/books.new'
import { Route as BooksCreateRouteImport } from './routes/books/create'
import { Route as BooksBookIdRouteImport } from './routes/books.$bookId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksNewRoute = BooksNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BooksRoute,
} as any)
const BooksCreateRoute = BooksCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => BooksRoute,
} as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/$bookId',
  path: '/$bookId',
  getParentRoute: () => BooksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/books': typeof BooksRouteWithChildren
  '/login': typeof LoginRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/books/create': typeof BooksCreateRoute
  '/books/new': typeof BooksNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/books': typeof BooksRouteWithChildren
  '/login': typeof LoginRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/books/create': typeof BooksCreateRoute
  '/books/new': typeof BooksNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/books': typeof BooksRouteWithChildren
  '/login': typeof LoginRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/books/create': typeof BooksCreateRoute
  '/books/new': typeof BooksNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/books'
    | '/login'
    | '/books/$bookId'
    | '/books/create'
    | '/books/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/books'
    | '/login'
    | '/books/$bookId'
    | '/books/create'
    | '/books/new'
  id:
    | '__root__'
    | '/'
    | '/books'
    | '/login'
    | '/books/$bookId'
    | '/books/create'
    | '/books/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BooksRoute: typeof BooksRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/new': {
      id: '/books/new'
      path: '/new'
      fullPath: '/books/new'
      preLoaderRoute: typeof BooksNewRouteImport
      parentRoute: typeof BooksRoute
    }
    '/books/create': {
      id: '/books/create'
      path: '/create'
      fullPath: '/books/create'
      preLoaderRoute: typeof BooksCreateRouteImport
      parentRoute: typeof BooksRoute
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof BooksRoute
    }
  }
}

interface BooksRouteChildren {
  BooksBookIdRoute: typeof BooksBookIdRoute
  BooksCreateRoute: typeof BooksCreateRoute
  BooksNewRoute: typeof BooksNewRoute
}

const BooksRouteChildren: BooksRouteChildren = {
  BooksBookIdRoute: BooksBookIdRoute,
  BooksCreateRoute: BooksCreateRoute,
  BooksNewRoute: BooksNewRoute,
}

const BooksRouteWithChildren = BooksRoute._addFileChildren(BooksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BooksRoute: BooksRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
